### ISSUE TITLE
Node 16 Deprecated

### ISSUE THREAD

**Issue by IamGreut** [xeol-io/xeol-action#27]
Upon using this action, the summary section of the workflow always provides the following annotation:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: xeol-io/xeol-action@v1.1.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

<img width="817" alt="Screenshot 2024-05-20 at 1 59 15 PM" src="https://github.com/xeol-io/xeol-action/assets/57777009/9c119c82-49c8-41f7-a6ce-5817369c1e56">

Is there any timeline to upgrading from Node 16?

**Comment by noqcks** [comment]
hey @IamGreut thanks for bringing this to our attention! 

I just updated the action to use node 20 in `v1.1.1`
