### ISSUE TITLE
Memory Constraints

### ISSUE THREAD

**Issue by IamGreut** [xeol-io/xeol-action#30]
When building a large docker image (5.8GB in this case), the XEOL step produces the following error:

> * failed to catalog: unable to load image: unable to use DockerDaemon source: unable to save image tar: Error response from daemon: write /var/lib/docker/tmp/docker-export-2345671101/blobs/sha256/2p923584c6accaac8a0970283aa856e8a8729f7c5183bb549b19a5c08c7: no space left on device

Is there a known way around this? I'm wondering if this is just a GitHub runner memory limitation rather than some other constraint, but want to confirm.

Found the same issue referenced [here](https://github.com/xeol-io/xeol/issues/295#issue-2124385168).

**Comment by noqcks** [comment]
can you try setting TMPDIR and see if that helps 

we dont currently have this setting documented but it looks like the same issue has faced grype users

https://github.com/anchore/grype/issues/533#issuecomment-993510384

**Comment by IamGreut** [comment]
Hey @noqcks 
Thanks for pointing that out. That did allow alteration of the path. 
This just turns out to be a legitimate memory constraint on the default GitHub runners.
